apiVersion: apps/v1
kind: Deployment
metadata:
  name: try
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try
  template:
    metadata:
      labels:
        app: try
    spec:
      containers:
      - image: okteto.dev/try:latest
        name: try
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a6cb2ac2-feb2-11ed-be56-0242ac120002"
        - name: Vless_Path
          value: "/dfgf45"
        - name: Vmess_UUID
          value: "a6cb2ac2-feb2-11ed-be56-0242ac120002"
        - name: Vmess_Path
          value: "/dfgf45"
        - name: Share_Path
          value: "/v2link"
